config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
 root "welcome#index"
 get 'sign_up', to: 'registrations#new'
 post 'sign_up', to: 'registrations#create'
 get 'sign_in', to: 'sessions#new'
 post 'sign_in', to: 'sessions#create', as: 'log_in'
 delete 'logout', to: 'sessions#destroy'
 get 'password', to: 'passwords#edit', as: 'edit_password'
 patch 'password', to: 'passwords#update'
 get 'password/reset', to: 'password_resets#new'
 post 'password/reset', to: 'password_resets#create'
 get 'password/reset/edit', to: 'password_resets#edit'
 patch 'password/reset/edit', to: 'password_resets#update'

 Rails.application.routes.draw do
  resources :tests do
    resources :questions do
      resources :answers
    end
  end
end



end

app/models/answer.rb
class Answer < ApplicationRecord
    belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    # makes Current.user accessible in view files.
    attribute :user
  end

app/models/question.rb
class Question < ApplicationRecord
    belongs_to :test
    has_many :answers, dependent: :destroy
    accepts_nested_attributes_for :answers, allow_destroy: true
  
    # Решта коду моделі Question
  end

app/models/test.rb
class Test < ApplicationRecord
    has_many :questions, dependent: :destroy
    accepts_nested_attributes_for :questions, allow_destroy: true
  
    # Решта коду моделі Test
  end

app/models/user.rb
class User < ApplicationRecord

     # adds virtual attributes for authentication
     has_secure_password
     # validates email
     validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: 'Invalid email' }


end

app/controllers/answer_controller.rb
class AnswersController < ApplicationController
    before_action :set_test
    before_action :set_question
    before_action :set_answer, only: [:show, :edit, :update, :destroy]
  
    def show
    end
  
    def new
      @answer = @question.answers.build
    end
  
    def create
      @answer = @question.answers.build(answer_params)
      if @answer.save
        redirect_to test_question_path(@test, @question)
      else
        render 'new'
      end
    end
  
    def edit
    end
  
    def update
      if @answer.update(answer_params)
        redirect_to test_question_path(@test, @question)
      else
        render 'edit'
      end
    end
  
    def destroy
      @answer.destroy
      redirect_to test_question_path(@test, @question)
    end
  
    private
  
    def set_test
      @test = Test.find(params[:test_id])
    end
  
    def set_question
      @question = @test.questions.find(params[:question_id])
    end
  
    def set_answer
      @answer = @question.answers.find(params[:id])
    end
  
    def answer_params
      params.require(:answer).permit(:title, :correctness)
    end
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_current_user
    def set_current_user
      # finds user with session data and stores it if present
      Current.user = User.find_by(id: session[:user_id]) if session[:user_id]
    end
    def require_user_logged_in!
      # allows only logged in user
      redirect_to sign_in_path, alert: 'You must be signed in' if Current.user.nil?
    end
  end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
    def new; end

    def create
        @user = User.find_by(email: params[:email])
        if @user.present?
          # send mail
          PasswordMailer.with(user: @user).reset.deliver_later
          # deliver_later is provided by ActiveJob
        end
        redirect_to root_path, notice: 'Please check your email to reset the password'
      end



    def edit
      # finds user with a valid token
      @user = User.find_signed!(params[:token], purpose: 'password_reset')
      rescue ActiveSupport::MessageVerifier::InvalidSignature
        redirect_to sign_in_path, alert: 'Your token has expired. Please try again.'
    end
    def update
      # updates user's password
      @user = User.find_signed!(params[:token], purpose: 'password_reset')
      if @user.update(password_params)
        redirect_to sign_in_path, notice: 'Your password was reset successfully. Please sign in'
        else
        render :edit
      end
    end
    private
    def password_params
      params.require(:user).permit(:password, :password_confirmation)
    end
  end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
    # allows only logged in users
    before_action :require_user_logged_in!
    def edit; end
    def update
      # update user password
      if Current.user.update(password_params)
        redirect_to root_path, notice: 'Password Updated'
      else
        render :edit
      end
    end
    private
    def password_params
      params.require(:user).permit(:password, :password_confirmation)
    end
  end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
    before_action :set_test
    before_action :set_question, only: [:show, :edit, :update, :destroy]
  
    def show
    end
  
    def new
      @question = @test.questions.build
    end
  
    def create
      @question = @test.questions.build(question_params)
      if @question.save
        redirect_to test_path(@test)
      else
        render 'new'
      end
    end
  
    def edit
    end
  
    def update
      if @question.update(question_params)
        redirect_to test_question_path(@test, @question)
      else
        render 'edit'
      end
    end
  
    def destroy
      @question.destroy
      redirect_to test_path(@test)
    end
  
    private
  
    def set_test
      @test = Test.find(params[:test_id])
    end
  
    def set_question
      @question = @test.questions.find(params[:id])
    end
  
    def question_params
      params.require(:question).permit(:title, :level)
    end
  end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
    # створення користувача
    def new
      @user = User.new
    end
    def create
      @user = User.new(user_params)
      if @user.save
      # збереження параметру user id в сесії
        session[:user_id] = @user.id
        redirect_to root_path, notice: 'Акаунт успішно створено'
      else
        render :new
      end
    end
    private
    def user_params
      # параметри користувача
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
  end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new; end
    def create
      user = User.find_by(email: params[:email])
      # finds existing user, checks to see if user can be authenticated
      if user.present? && user.authenticate(params[:password])
      # sets up user.id sessions
        session[:user_id] = user.id
        redirect_to root_path, notice: 'Logged in successfully'
      else
        flash.now[:alert] = 'Invalid email or password'
        render :new
      end
    end
    def destroy
      # deletes user session
      session[:user_id] = nil
      redirect_to root_path, notice: 'Logged Out'
    end
  end

app/controllers/testsController.rb
class TestsController < ApplicationController
  before_action :set_test, only: [:show, :edit, :update]

  def index
    @tests = Test.all
  end

  def show
  end

  def new
    @test = Test.new
  end

  def destroy
    @test= Еest.find(params[:id])
    @test.destroy
    redirect_to tests_url, notice: 'Test was successfully destroyed.'
  end

  def create
    @test = Test.new(test_params)

    if @test.save
      redirect_to @test, notice: 'Test was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @test.update(test_params)
      redirect_to @test, notice: 'Test was successfully updated.'
    else
      render :edit
    end
  end

  private

  def set_test
    @test = Test.find(params[:id])
  end

  def test_params
    params.require(:test).permit(:title, :subject, :time_start, :time_finish, :time_limit, :max_grade, :creator_id)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/answers/new.html.erb
<h1>Create a New Answer</h1>
  
<%= form_for [@question, @answer] do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :correctness %>
  <%= f.check_box :correctness %>

  <%= f.submit "Create Answer" %>
<% end %>

app/views/answers/show.html.erb
<h1><%= @answer.title %></h1>
<p>Correctness: <%= @answer.correctness %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bachv3</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <nav style="background-color: pink; padding: 10px;">
  <ul style="display: flex; list-style-type: none; justify-content: space-between; align-items: center;">
    <li><%= link_to 'Головна ', root_path %></li>
    <li><%= link_to 'Тести ', tests_path %></li>
    <li><%= link_to 'Створити тест ', new_test_path %></li>
    <li style="margin-left: auto;">
      <% if Current.user %>
        <span>Вхід здійсненно як: <%= Current.user.email %></span>
        <div>
          <%= link_to 'Змінити пароль', edit_password_path %>
          <%= button_to 'Вихід', logout_path, method: :delete, class: 'logout-button' %>
        </div>
      <% else %>
        <div>
          <%= link_to 'Зареєструватись', sign_up_path %>
          <span>або</span>
          <%= link_to 'Увійти', sign_in_path %>
        </div>
      <% end %>
    </li>
  </ul>
</nav>
  <body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= yield %>
</body>
  </body>
</html>

app/views/password_resets/edit.html.erb
<h1>Reset your password?</h1>
  <%= form_with model: @user, url: password_reset_edit_path(token: params[:token]) do |f| %>
    <p>
    <%= f.label 'password:' %><br />
    <%= f.password_field :password %>
    </p>
    <p>
    <%= f.label 'password_confirmation:' %><br />
    <%= f.password_field :password_confirmation %>
    </p>
    <p>
    <%= f.submit 'Reset Password' %>
    </p>
  <% end %>

app/views/password_resets/new.html.erb
<h1>Forgot your password?</h1>
<%= form_with url: password_reset_path do |f| %>
  <p>
  <%= f.label 'email:' %><br />
  <%= f.text_field :email %>
  </p>
  <p>
  <%= f.submit 'Reset Password' %>
  </p>
<% end %>

app/views/questions/new.html.erb
<h1>Create Question</h1>

<%= form_with(model: @question, local: true) do |form| %>
  <%= form.label :title %>
  <%= form.text_field :title %>

  <%= form.label :level %>
  <%= form.number_field :level %>

  <h2>Answers</h2>
  <%= form.fields_for :answers do |answer_form| %>
    <%= answer_form.label :title %>
    <%= answer_form.text_field :title %>

    <%= answer_form.label :correctness %>
    <%= answer_form.check_box :correctness %>
  <% end %>

  <%= form.submit %>
<% end %>

app/views/questions/show.html.erb
<h1><%= @question.title %></h1>
<p>Level: <%= @question.level %></p>

app/views/welcome/index.html.erb
<style>
  body {
    background-color: #f9f9f9;
    font-family: Arial, sans-serif;
  }

  .container {
    max-width: 1200px;
    margin: 0 auto;
    padding: 20px;
    background-color: #fff;
    border: 1px solid #ccc;
    border-radius: 4px;
    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
  }

  h1 {
    font-size: 24px;
    font-weight: bold;
    color: #333;
    margin-bottom: 20px;
  }

  p {
    color: #666;
    margin-bottom: 10px;
  }
</style>

<div class="container">
  <h1>Система для перевірки знань</h1>

  <p>Система для оцінювання знань ставить на перший план потреби та вимоги користувачів, а також забезпечує повний спектр функцій управління процесом навчання.</p>
  <p>У навчальних закладах студенти здобувачі освіти часто стикаються з труднощами у проведенні тестування рівня освоєння знань, що може викликати невиконання навчального плану та ухилення від деяких дисциплін.</p>
  <p>Цей факт стає все більш серйозним, зважаючи на важливість деяких дисциплін для професійного розвитку здобувачів освіти у науковій галузі. Тому, цікаво дослідити фактори, які впливають на труднощі студентів, щоб визначити стратегії подолання цих проблем.</p>
  <p>Створювана система надає можливість користувачам ефективно керувати усіма аспектами циклу навчання, включаючи отримання загальної інформації про користувачів, ідентифікацію потенційних користувачів, подальшу роботу з ними та підтримку постійних клієнтів.</p>
</div>